### ISSUE TITLE
Margin Issue for otp/add item dialogboxes

### ISSUE THREAD

**Issue by shriram-joshi** [unc0ded/ShopEasy#16]
There is an issue adding margins to the otp and add to inventory dialog box. The dialog boxs neecd some sort of margi/padding but adding those fields doesnt help. Need to look into how to fix this.
![WhatsApp Image 2020-07-24 at 23 45 31](https://user-images.githubusercontent.com/56927348/88422567-15431700-ce08-11ea-908f-448303a12171.jpeg)

**Comment by unc0ded** [comment]
Weird, everything looks okay on my phone. Can I get a screen for the add item dialogbox?

**Comment by shriram-joshi** [comment]
This one looks better still the heading needs horizontal margins
![Screenshot_20200725-095454_ShopEasy.jpg](https://user-images.githubusercontent.com/56927348/88448621-4b5eb600-ce5d-11ea-8c9f-c1ceae7aad15.jpg)
