### ISSUE TITLE
Making POJO model of Vendor

### ISSUE THREAD

**Issue by shriram-joshi** [unc0ded/ShopEasy#17]
Today I changed the model of Customer to match the db in my latest commit to mvvm-migration branch. 
This change includes creating 4 model pojo classes Customer.java, Address.java, Name.java and Credentials.java. These classes were made from http://www.jsonschema2pojo.org/ using the JsonObject string of a Customer from Firestore Database. 
Ideally we should also convert the Vendor class to fit the database model. This is more efficient as we dont need to create hashmaps to post data of users while registration/updating their details and makes the code for sign up more easy.

**Comment by shriram-joshi** [comment]
I have completed this will close this issue with the next commit

**Comment by unc0ded** [comment]
I was thinking maybe the Name and Credentials POJOs aren't needed. I have structured the database like this, I don't think the nesting is necessary..
![Screenshot (371)](https://user-images.githubusercontent.com/56927116/88790017-20ee5f00-d1b5-11ea-8493-b826ab67a5b6.png)
What do you think?

**Comment by shriram-joshi** [comment]
Yes sure. I'll re-structure it. Not a big deal. Just send me the structure for the vendor and customer and I'll change it accordingly to match the api.

**Comment by unc0ded** [comment]
![Screenshot (373)](https://user-images.githubusercontent.com/56927116/88794102-90674d00-d1bb-11ea-830d-97842c672420.png)
![Screenshot (372)](https://user-images.githubusercontent.com/56927116/88794108-91987a00-d1bb-11ea-8076-6d6a8f72aaa7.png)

I hope this is fine. Ignore the id field, mongodb automatically adds it.

**Comment by shriram-joshi** [comment]
Seems fine just make it in camel case. Like shopname should be shopName so that it matches the java object naming protocol.
Because when you convert a Java object to a JsonObject it sets the keys according to the object name in the Pojo

**Comment by shriram-joshi** [comment]
Also the locality attribute for a Customer is not needed.
Check the current Firestore key naming for reference.

**Comment by unc0ded** [comment]
> Seems fine just make it in camel case. Like shopname should be shopName so that it matches the java object naming protocol.
> Because when you convert a Java object to a JsonObject it sets the keys according to the object name in the Pojo

Done.
